routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

// Handles Questions CRUD
Route::resource('questions', \App\Http\Controllers\QuestionsController::class)->except('show');
Route::get('questions/{slug}', [\App\Http\Controllers\QuestionsController::class, 'show']);

// Handles Mark as Best Answer Feature
Route::put('questions/{question}/answers/{answer}/best-answer', [\App\Http\Controllers\QuestionAnswersController::class, 'markAsBest'])->name('markAsBest');

// Handles Answers CRUD
Route::middleware(['auth'])->group(function() {
    Route::get('questions/{question}/answer/create', [\App\Http\Controllers\QuestionAnswersController::class, 'create'])->name('questionAnswer.create');
    Route::post('questions/{question}/answer', [\App\Http\Controllers\QuestionAnswersController::class, 'store'])->name('questionAnswer.store');
    Route::get('question/{question}/answer/{answer}/edit', [\App\Http\Controllers\QuestionAnswersController::class, 'edit'])->name('questionAnswer.edit');
    Route::put('question/{question}/answer/{answer}/update', [\App\Http\Controllers\QuestionAnswersController::class, 'update'])->name('questionAnswer.update');
    Route::delete('questions/{question}/answer/{answer}/delete', [\App\Http\Controllers\QuestionAnswersController::class, 'destroy'])->name('questionAnswer.destroy');
});

// Handles Mark As Fav & UnFav Question Feature
Route::post('questions/{question}/favorite', [\App\Http\Controllers\FavoritesController::class, 'store'])->name('questions.favorite');
Route::delete('questions/{question}/unfavorite', [\App\Http\Controllers\FavoritesController::class, 'destroy'])->name('questions.unfavorite');

// Handles Votes System for Question and Answers
Route::post('questions/{question}/vote/{vote}', [\App\Http\Controllers\VotesController::class, 'voteQuestion'])->name('questions.vote');
Route::post('answers/{answer}/vote/{vote}', [\App\Http\Controllers\VotesController::class, 'voteAnswer'])->name('answers.vote');


Route::get('/dashboard', function () {
    return view('dashboard');
})->middleware(['auth'])->name('dashboard');

require __DIR__.'/auth.php';

app/Models/Question.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Str;

class Question extends Model
{
    protected $guarded = [];

    use HasFactory;

    /**
     * Mutators
     */

    public function setTitleAttribute($title){
        $this->attributes['title'] = $title;
        $this->attributes['slug'] = Str::slug($title);
    }

    /**
     * Accessors
     */

    public function getUrlAttribute() {
        return "questions/$this->slug";
    }

    public function getCreatedDateAttribute() {
        return $this->created_at->diffForHumans();
    }

    public function getStylesForAnswerAttribute(){
        if($this->answers_count > 0){
            if($this->best_answer_id){
                return "has-best-answer";
            }   else    {
                return "answered";
            }
        }
        return "unanswered";
    }

    public function getIsFavoriteAttribute()
    {
        return $this->favorites()->where(['user_id'=> auth()->id()])->count() > 0;
    }

    public function getFavoritesCountAttribute()
    {
        return $this->favorites->count();
    }

    /**
     *
     */
    public function markAsBest(Answer $answer)
    {
        $this->best_answer_id = $answer->id;
        $this->save();
    }

    public function vote(int $vote)
    {
        $this->votes()->attach(auth()->id(), ['vote'=>$vote]);
        if($vote > 0) {
            $this->increment('votes_count');
        } else {
            $this->decrement('votes_count');
        }
    }

    public function updateVote(int $vote)
    {
        $this->votes()->updateExistingPivot(auth()->id(), ['vote'=> $vote]);
        if($vote > 0) {
            $this->increment('votes_count');
            $this->increment('votes_count');
        } else {
            $this->decrement('votes_count');
            $this->decrement('votes_count');
        }
    }

    public function hasMarkedUpVote(User $user)
    {
        return $this->votes()->where('user_id', $user->id)->where('vote', 1)->exists();
    }

    public function hasMarkedDownVote(User $user)
    {
        return $this->votes()->where('user_id', $user->id)->where('vote', -1)->exists();
    }

    public function hasVoted(User $user)
    {
        return $this->votes()->where('user_id', $user->id)->exists();
    }

    /**
     * Relationship Methods
     */

    public function owner(){
        return $this->belongsTo(User::class, 'user_id');
    }

    public function answers()
    {
        return $this->hasMany(Answer::class);
    }

    public function favorites()
    {
        return $this->belongsToMany(User::class)->withTimestamps();
    }

    public function votes()
    {
        return $this->morphToMany(User::class, 'vote')->withTimestamps();
    }

}

app/Models/User.php
<?php

namespace App\Models;

// use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function getAvatarAttribute()
    {
        $name = $this->name;
        return "https://ui-avatars.com/api/?background=random&size=40&rounded=true&name={$name}";
    }

    /**
     * Relationship Methods
     */

    public function questions(){
        return $this->hasMany(Question::class);
    }

    public function answers()
    {
        return $this->hasMany(Answer::class);
    }

    public function favorites()
    {
        return $this->belongsToMany(User::class)->withTimestamps();
    }

    public function votesQuestions()
    {
        return $this->morphedByMany(Question::class, 'vote')->withTimestamps();
    }
    public function votesAnswers()
    {
        return $this->morphedByMany(Answer::class, 'vote')->withTimestamps();
    }

}

app/Http/Controllers/QuestionsController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\Questions\UpdateQuestionRequest;
use App\Http\Requests\Questions\CreateQuestionRequest;
use App\Models\Question;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Gate;

class QuestionsController extends Controller
{
    public function __construct()
    {
        $this->middleware(['auth'])->except(['index', 'show']);
    }

    public function index()
    {
        $questions = Question::with('owner')->latest()->paginate(10);
        return view('questions.index', compact(['questions']));
    }

    public function create()
    {
        return view('questions.create');
    }

    public function store(CreateQuestionRequest $request)
    {
        //dd($request);
        auth()->user()->questions()->create([
            'title' => $request->title,
            'body' => $request->body
        ]);

        session()->flash('success', 'Question has been reported to all our expert users!');
        return redirect(route('questions.index'));
    }

    public function show(Question $question)
    {
        //dd($question);
        $question->increment('views_count');
        return view('questions.show', compact(['question']));
    }

    public function edit(Question $question)
    {
        if($this->authorize('update', $question)) {
            return view('questions.edit', compact(['question']));
        }
        return abort(403);
    }

    public function update(UpdateQuestionRequest $request, Question $question)
    {
        if($this->authorize('update', $question)) {
            $question->update([
                'title' => $request->title,
                'body' => $request->body
            ]);
            session()->flash('success', 'Question has been updated and will be answered accordingly soon!');
            return redirect(route('questions.index'));
        }
        return abort(403);
    }

    public function destroy(Question $question)
    {
        if($this->authorize('delete', $question)) {
            $question->delete();
            session()->flash('success', 'Question deleted! Why did you waste time by asking? :|');
            return redirect(route('questions.index'));
        }
        return abort(403);
    }
}

resources/views/questions/create.blade.php
@extends('frontend-layouts.app')

@section('page-level-styles')
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/trix/1.3.1/trix.css" />
@endsection

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">
                        <h3>Ask a Question</h3>
                    </div>
                    <div class="card-body">
                        <form action="{{ route('questions.store') }}" method="POST">
                            @csrf
                            <div class="form-group mb-3">
                                <label for="title">Title</label>
                                <input type="text"
                                       class="form-control {{ $errors->has('title') ? 'is-invalid' : '' }}"
                                       value="{{ old('title') }}"
                                       placeholder="Enter Question Title"
                                       name="title" id="title" />
                                @error('title')
                                    <span class="text-danger">{{ $message }}</span>
                                @enderror
                            </div>
                            <div class="form-group mb-3">
                                <label for="body">Question</label>
                                <input type="hidden"
                                       value="{{ old('body') }}"
                                       class="form-control"
                                       name="body" id="body" />
                                <trix-editor input="body"
                                             placeholder="Ask your question"
                                             class="form-control {{ $errors->has('body') ? 'is-invalid' : '' }}">
                                </trix-editor>
                                @error('body')
                                    <span class="text-danger">{{ $message }}</span>
                                @enderror
                            </div>
                            <div class="form-group mb-3">
                                <input type="submit" value="Ask Experts" class="btn btn-outline-success">
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection


@section('page-level-scripts')
    <script src="https://cdnjs.cloudflare.com/ajax/libs/trix/1.3.1/trix.js"></script>
@endsection

resources/views/questions/edit.blade.php
@extends('frontend-layouts.app')

@section('page-level-styles')
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/trix/1.3.1/trix.css" />
@endsection

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">
                        <h3>Ask a Question</h3>
                    </div>
                    <div class="card-body">
                        <form action="{{ route('questions.update', $question) }}" method="POST">
                            @csrf
                            @method('PUT')
                            <div class="form-group mb-3">
                                <label for="title">Title</label>
                                <input type="text"
                                       class="form-control {{ $errors->has('title') ? 'is-invalid' : '' }}"
                                       value="{{ old('title', $question->title) }}"
                                       placeholder="Enter Question Title"
                                       name="title" id="title" />
                                @error('title')
                                <span class="text-danger">{{ $message }}</span>
                                @enderror
                            </div>
                            <div class="form-group mb-3">
                                <label for="body">Question</label>
                                <input type="hidden"
                                       value="{{ old('body', $question->body) }}"
                                       class="form-control"
                                       name="body" id="body" />
                                <trix-editor input="body"
                                             placeholder="Ask your question"
                                             class="form-control {{ $errors->has('body') ? 'is-invalid' : '' }}">
                                </trix-editor>
                                @error('body')
                                <span class="text-danger">{{ $message }}</span>
                                @enderror
                            </div>
                            <div class="form-group mb-3">
                                <input type="submit" value="Ask Experts" class="btn btn-outline-success">
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

@section('page-level-scripts')
    <script src="https://cdnjs.cloudflare.com/ajax/libs/trix/1.3.1/trix.js"></script>
@endsection

resources/views/questions/index.blade.php
@extends('frontend-layouts.app')

@section('page-level-styles')
    <style>
        .statistics strong {
            font-size: 1.2rem;
        }

        .statistics .answers {
            padding: 10px;
            border-radius: 5px;
        }

        .statistics .answers.answered {
            border: solid 1px green;
            color: green;
        }

        .statistics .answers.has-best-answer {
            border: solid 1px green;
            background: green;
            color: white;
        }

        .statistics .answers.unanswered {
            border: solid 1px darkred;
            color: darkred;
        }
    </style>
@endsection

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="d-flex justify-content-end">
                <a href="{{ route('questions.create') }}" class="btn btn-outline-primary mb-3">Ask a Question!</a>
            </div>
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">All Questions</div>
                    @foreach($questions as $question)
                        <div class="card-body">
                            <div class="row">
                                <div class="col-md-1">
                                    <div class="d-flex flex-column statistics">
                                        <div class="votes text-center mb-3">
                                            <strong class="d-block">{{ $question->votes_count }}</strong>
                                            Votes
                                        </div>
                                        <div class="answers text-center mb-3 {{ $question->styles_for_answer }}">
                                            <strong class="d-block">
                                                {{ $question->answers_count }}
                                            </strong>
                                            Answers
                                        </div>
                                        <div class="views text-center mb-3">
                                            <strong class="d-block">
                                                {{ $question->views_count }}
                                            </strong>
                                            Views
                                        </div>
                                    </div>
                                </div>
                                <div class="col-md-11">
                                    <h2 class="card-title">
                                        <div class="d-flex justify-content-between">
                                            <a href="{{ $question->url }}">{{ $question->title }}</a>
                                            <div>
                                                @can('update', $question)
                                                    <a href="{{ route('questions.edit', $question) }}"
                                                       class="btn btn-warning">
                                                        Edit
                                                    </a>
                                                @endcan
                                                @can('delete', $question)
                                                    <form action="{{ route('questions.destroy', $question) }}"
                                                          class="d-inline"
                                                          method="POST">
                                                        @csrf
                                                        @method('DELETE')
                                                        <input type="submit" class="btn btn-danger" value="Delete"/>
                                                    </form>
                                                @endcan

                                            </div>
                                        </div>
                                    </h2>
                                    <p>
                                        <small>Asked By: <a href="#">{{ $question->owner->name }}</a></small>
                                        <span class="text-muted">{{ $question->created_date }}</span>
                                    </p>
                                    <p class="card-text">
                                        {!!  \Illuminate\Support\Str::limit($question->body, 250) !!}
                                    </p>
                                </div>
                            </div>
                        </div>
                        <hr/>
                    @endforeach
                    <div class="card-footer">
                        {{ $questions->links() }}
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/questions/show.blade.php
@extends('frontend-layouts.app')

@section('page-level-styles')
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.css" />
@endsection

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">
                    <h1>{{ $question->title }}</h1>
                </div>
                <div class="card-body">
                    {!! $question->body !!}
                </div>
                <div class="card-footer">
                    <div class="d-flex justify-content-between mr-3">
                        <div class="d-flex">
                            <div>
                                @auth
                                    <form action="{{ route('questions.vote', [$question, 1]) }}" method="POST">
                                        @csrf
                                        <button type="submit"
                                                title="Vote Up"
                                                class="vote-up d-block text-center {{ $question->hasMarkedUpVote(auth()->user()) ? ' text-success' : 'text-dark'}} border-0">
                                            <i class="fa fa-caret-up fa-3x"></i>
                                        </button>
                                    </form>
                                    <h4 class="m-0 text-muted text-center">{{ $question->votes_count }}</h4>
                                    <form action="{{ route('questions.vote', [$question, -1]) }}" method="POST">
                                        @csrf
                                        <button type="submit"
                                                title="Vote Down"
                                                class="vote-down d-block text-center {{ $question->hasMarkedDownVote(auth()->user()) ? ' text-danger' : 'text-dark'}} border-0">
                                            <i class="fa fa-caret-down fa-3x"></i>
                                        </button>
                                    </form>
                                @else
                                    <a href="{{ route('login') }}" title="Vote Up" class="vote-up d-block text-center text-dark">
                                        <i class="fa fa-caret-up fa-3x"></i>
                                    </a>
                                    <h4 class="m-0 text-muted">{{ $question->votes_count }}</h4>
                                    <a href="{{ route('login') }}" title="Vote Down" class="vote-down d-block text-center text-dark">
                                        <i class="fa fa-caret-down fa-3x"></i>
                                    </a>
                                @endauth
                            </div>
                            <div class="mt-3 ms-3">
                                @can('markAsFavorite', $question)
                                        @if($question->is_favorite)
                                            <form action="{{ route('questions.unfavorite', $question) }}" method="POST">
                                                @csrf
                                                @method('DELETE')
                                                <button type="submit" title="Mark as Fav" class="favorite d-block text-center mb-2 border-0">
                                                    <i class="fa fa-star fa-2x text-warning"></i>
                                                </button>
                                            </form>
                                        @else
                                            <form action="{{ route('questions.favorite', $question) }}" method="POST">
                                                @csrf
                                                <button type="submit" title="Mark as Fav" class="favorite d-block text-center mb-2 border-0">
                                                    <i class="fa fa-star fa-2x text-dark"></i>
                                                </button>
                                            </form>
                                        @endif
                                        <h4 class="text-muted text-center">{{ $question->favorites_count }}</h4>
                                    @endcan
                            </div>
                        </div>
                        <div class="d-flex flex-column">
                            <div class="text-end">
                                Asked {{ $question->created_date }}
                            </div>
                            <div class="d-flex mt-2">
                                <div>
                                    <img src="{{ $question->owner->avatar }}">
                                </div>
                                <div class="mt-2 ms-2">
                                    {{ $question->owner->name }}
                                </div>
                            </div>
                            <div class="text-end mt-2">
                                <a href="{{ route('questionAnswer.create', $question) }}"
                                    class="btn btn-primary">
                                    Give an Answer
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    @include('answers.index')
</div>
@endsection